### ISSUE TITLE
Foundation course - Bullet points not showing

### ISSUE THREAD

**Issue by JellePraet** [EHDEN/Academy#37] opened 2019-07-24 08:04 UTC
@PRijnbeek Could you look into the issue that bullet points of the Foundation Course are not showing correctly?

**Comment by PRijnbeek** [comment] 2019-07-24 10:15
This is a CSS bug in the template. Work around:

1) Open the HTML view (click on downward arrow and then on the <>) as shown here:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/7252105/61785463-03e9b800-ae0c-11e9-89b6-05cf2312dbf1.png">

2) The start of the ul (lists) should look like in the screenshot (add the padding)

The end result:

<img width="997" alt="image" src="https://user-images.githubusercontent.com/7252105/61785642-6cd13000-ae0c-11e9-8f75-03ff92c10bca.png">


@lhjohn the problem is that without the span the bullet point is just outside the visible window and you only see a small dot (end of the bullet). Ideally the span is add in the Edwiser css file for the <ul> then this is solved everywhere. Can you ask Edwiser how to fix this?

**Comment by PRijnbeek** [comment] 2019-07-24 10:20
Before: 

<img width="63" alt="image" src="https://user-images.githubusercontent.com/7252105/61785924-fc76de80-ae0c-11e9-86d1-fa072d4a3f5e.png">

After adding the padding

<img width="63" alt="image" src="https://user-images.githubusercontent.com/7252105/61786047-3ba52f80-ae0d-11e9-9ab0-d583b17123e4.png">

**Comment by PRijnbeek** [comment] 2019-07-24 10:24
@JellePraet I think i fixed all of them if i missed some please post this in the issue.

**Comment by PRijnbeek** [comment] 2019-07-25 18:47
Seem fine now so closing this one.

**Closed as completed by PRijnbeek** 2019-07-25 18:47 UTC
